### ISSUE TITLE
Django admin 500 when searching through Onfido.Event

### ISSUE THREAD

**Issue by djm** [yunojuno/django-onfido#12]
The `resource_id` field was renamed and migrated to `onfido_id` but the Admin.search_fields attribute was [never updated](https://github.com/yunojuno/django-onfido/blob/4bb717f8178711438c12d538ad8e0551ffd3b8c3/onfido/admin.py#L184).

It simply needs to be renamed to `onfido_id`.

I would submit a PR but I'm aware of the current 1.9 blocker, let me know how fixing this will fit in to that.

**Comment by hugorodgerbrown** [comment]
Fixed in both master (1.9) and django-1.8 branch. 1.8 version released to PyPI as 0.8.1.
